spring:
  application:
    name: demo-consumer # Spring 应用名
server:
  port: 28080 # 服务器端口。默认为 8080

eureka:
  client:
    register-with-eureka: true # 注册到 Eureka-Server，默认为 true
    fetch-registry: true # 从 Eureka-Server 获取注册表，默认为 true
    service-url:
      defaultZone: http://eureka:simon2021@127.0.0.1:8761/eureka/

